const TERM_ID = "TERM_ID"
const RECHAGE_ACCOUNT = "RECHAGE_ACCOUNT"
const START_ROUT_LENGTH = "START_ROUT_LENGTH"
const LOCAL_ORDER_INFO = "LOCAL_ORDER_INFO"
const PAY_TIP = "PAY_TIP"
const TERMID_PARTNERUID = "TERMID_PARTNERUID"
const HW_JSSDK_OPENID = "HW_JSSDK_OPENID"
const HW_JSSDK_ACCESS_TOKEN = "HW_JSSDK_ACCESS_TOKEN"
const IS_EXIST_HBS = "IS_EXIST_HBS"
const PLATUID = "PLATUID"

const COUPON = "COUPON"


export {
    TERM_ID,
    START_ROUT_LENGTH,
    LOCAL_ORDER_INFO,
    RECHAGE_ACCOUNT,
    PAY_TIP,
    TERMID_PARTNERUID,
    HW_JSSDK_OPENID,
    HW_JSSDK_ACCESS_TOKEN,
    IS_EXIST_HBS,
    PLATUID,
    COUPON
}
